#pragma once
#include "common-chax.h"
#include "skill-system.h"
#include "event-rework.h"
#include "constants/skills.h"
#define USE_TOA_DEFS
#include "constants/TOA_characters.h"
#include "constants/TOA_event-flags.h"
#include "TChax.h"
#include "constants/texts.h"