#include "Ch6.h"

const struct ROMChapterData Ch6Chapter = {
	.map = {
		.obj1Id = 1,
		.obj2Id = 0,
		.paletteId = 2,
		.tileConfigId = 3,
		.mainLayerId = 22,
		.objAnimId = 5,
		.paletteAnimId = 0,
		.changeLayerId = 23,
	},
	.initialFogLevel = 0,
	.hasPrepScreen = FALSE,
	.chapTitleId = 7, //ch6 complicit route
	.chapTitleIdInHectorStory = 9, //ch9 canon route
	.initialPosX = 13,
	.initialPosY = 25,
	.initialWeather = WEATHER_FINE,
	.battleTileSet = 0,
	.easyModeLevelMalus = 0,
	.difficultModeLevelBonus = 0,
	.normalModeLevelMalus = 1,
	.mapBgmIds = {
		[MAP_BGM_BLUE] = 13,
		[MAP_BGM_RED] = 21,
		[MAP_BGM_GREEN] = 15,
		[MAP_BGM_BLUE_HECTOR] = 13,
		[MAP_BGM_RED_HECTOR] = 21,
		[MAP_BGM_GREEN_HECTOR] = 15,
		[MAP_BGM_BLUE_GREEN_ALT] = 65535,
		[MAP_BGM_RED_ALT] = 65535,
		[MAP_BGM_PROLOGUE_LYN] = 11,
		[MAP_BGM_PROLOGUE] = 65535,
		[MAP_BGM_PROLOGUE_HECTOR] = 65535,
	},
	.mapCrackedWallHeath = 50,
	.turnsForTacticsRankAInEliwoodStory = {
		[0] = 5,
		[1] = 5,
	},
	.turnsForTacticsRankAInHectorStory = {
		[0] = 5,
		[1] = 5,
	},
	.turnsForTacticsRankBInEliwoodStory = {
		[0] = 6,
		[1] = 6,
	},
	.turnsForTacticsRankBInHectorStory = {
		[0] = 6,
		[1] = 6,
	},
	.turnsForTacticsRankCInEliwoodStory = {
		[0] = 7,
		[1] = 7,
	},
	.turnsForTacticsRankCInHectorStory = {
		[0] = 7,
		[1] = 7,
	},
	.turnsForTacticsRankDInEliwoodStory = {
		[0] = 8,
		[1] = 8,
	},
	.turnsForTacticsRankDInHectorStory = {
		[0] = 8,
		[1] = 8,
	},
	.unk3D = 0,
	.gainedExpForExpRankAInEliwoodStory = {
		[0] = 100,
		[1] = 100,
	},
	.gainedExpForExpRankAInHectorStory = {
		[0] = 100,
		[1] = 100,
	},
	.gainedExpForExpRankBInEliwoodStory = {
		[0] = 80,
		[1] = 80,
	},
	.gainedExpForExpRankBInHectorStory = {
		[0] = 80,
		[1] = 80,
	},
	.gainedExpForExpRankCInEliwoodStory = {
		[0] = 60,
		[1] = 60,
	},
	.gainedExpForExpRankCInHectorStory = {
		[0] = 60,
		[1] = 60,
	},
	.gainedExpForExpRankDInEliwoodStory = {
		[0] = 40,
		[1] = 40,
	},
	.gainedExpForExpRankDInHectorStory = {
		[0] = 40,
		[1] = 40,
	},
	.unk5E = CH_6_MAIN_MENU_CH_NAME,
	.goldForFundsRankInEliwoodStory = {
		[0] = 1060,
		[1] = 1060,
	},
	.goldForFundsRankInHectorStory = {
		[0] = 1060,
		[1] = 1060,
	},
	.chapTitleTextId = CH_6_ROUTE_A_CH_NAME,
	.chapTitleTextIdInHectorStory = CH_6_ROUTE_B_CH_NAME,
	.mapEventDataId = 24,
	.gmapEventId = 8,
	.divinationTextIdBeginning = 0,
	.divinationTextIdInEliwoodStory = 0,
	.divinationTextIdInHectorStory = 0,
	.divinationTextIdEnding = 0,
	.divinationPortrait = 0,
	.divinationFee = 0,
	.prepScreenNumber = 0,
	.prepScreenNumberInHectorStory = 0,
	.merchantPosX = 255,
	.merchantPosXInHectorStory = 255,
	.merchantPosY = 0,
	.merchantPosYInHectorStory = 0,
	.victorySongEnemyThreshold = 1,
	.fadeToBlack = FALSE,
	.statusObjectiveTextId = 0x19c,
	.goalWindowTextId = 0x1b0,
	.goalWindowDataType = GOAL_TYPE_DEFENSE,
	.goalWindowEndTurnNumber = 12,
	.protectCharacterIndex = CHARACTER_BOSS_ASKON_EMPEROR,
	.destPosX = 255,
	.destPosY = 0,
	.unk91 = 0,
	.unk92 = 0,
	.unk93 = 0,
};
